### ISSUE TITLE
Keep anchors

### ISSUE THREAD

**Issue by NARKOZ** [dkhamsing/frankenstein#10]
Currently frankenstein doesn't keep anchors in replaced links.

Example:

```
https://github.com/rwldrn/idiomatic.js#readme

https://github.com/rwaldron/idiomatic.js
```

**Comment by dkhamsing** [comment]
Tou are right, thanks for the report

**Comment by dkhamsing** [comment]
Test: https://gist.github.com/dd8cf18b3cd1112c0766
