### ISSUE TITLE
Support HTTP auth

### ISSUE THREAD

**Issue by erg0dic** [dkhamsing/frankenstein#11]
Apparently this is not possible by providing user:password in the URI:

```
http://user:pass@example.com
```

but faraday issue tracker shows how to accomplish this with a connection object:
https://github.com/lostisland/faraday/issues/426

**Comment by dkhamsing** [comment]
Thanks for the report :smile:

**Comment by dkhamsing** [comment]
@erg0dic do you have a test server with credentials I can try?

**Comment by dkhamsing** [comment]
Will close this unless there is more support/demand
Thanks :-)
