### ISSUE TITLE
Use flavored markdown diff highlighting 

### ISSUE THREAD

**Issue by stefanbuck** [dkhamsing/frankenstein#15]
Instead of using a table to display the changes

Was | Now
--- | --- 
https://github.com/tj/supertest | https://github.com/visionmedia/supertest

... you could use flavored markdown diff highlighting!

```diff
-https://github.com/tj/supertest 
+https://github.com/visionmedia/supertest
```

What do you think?

**Comment by dkhamsing** [comment]
Looks pretty interesting, let me take a look

**Comment by dkhamsing** [comment]
One problem is a reviewer wouldn't be able to click on the links

**Comment by stefanbuck** [comment]
Good points. Thanks for that feedback!

**Comment by dkhamsing** [comment]
Thank you for the suggestion!
