### ISSUE TITLE
Issues with some links

### ISSUE THREAD

**Issue by RichardLitt** [dkhamsing/frankenstein#18]
Here is my example link which shouldn't have been changed this way:

### Other Corrected URLs 
Was | Now 
--- | --- 
https://godoc.org/github.com/ipfs/go-libp2p-crypto | /github.com/libp2p/go-libp2p-crypto 

Should have changed to: https://godoc.org/github.com/libp2p/go-libp2p-crypto

**Comment by dkhamsing** [comment]
I have seen this issue, it is not supported at the moment, 
Should be filed in awesome_bot

I will do it

**Comment by RichardLitt** [comment]
Thanks!
