### ISSUE TITLE
Gem install frankenstein?

### ISSUE THREAD

**Issue by m1guelpf** [dkhamsing/frankenstein#20]
For fastest integration, could you make an easy install.
Like gem install && frankenstein
instead of cloning and building.

**Comment by dkhamsing** [comment]
sorry, the code for this is a mess
not sure it is ready for rubygem

how are you using it??

**Comment by m1guelpf** [comment]
I would like to use it with Travis for some awesome lists, like bayandin/awesome-awesomeness and m1guelpf/awesome-pentester

**Comment by dkhamsing** [comment]
oh wow i see
that's advanced

have you gotten it to work with cloning the project?

**Comment by dkhamsing** [comment]
and travis
