### ISSUE TITLE
More descriptive PRs

### ISSUE THREAD

**Issue by rshipp** [dkhamsing/frankenstein#6]
Hi! Cool project, this is really useful.

Your @ReadmeCritic opened a [Pull Request ](https://github.com/rshipp/awesome-malware-analysis/pull/22) on one of my repos. Before reading about the project, I was a little confused about why it was making those changes. If you could include a little more explanation in the PR title, like "**Updated README URLs based on HTTP 3xx redirects**" (if that's correct), that would make it much more clear.

Also, since as the repo maintainer I would like to double-check the new links before merging the PR, it would be nice to have clickable links so I can see the redirects are correct. Something like this with [GFM tables](https://help.github.com/articles/github-flavored-markdown/#tables) would be great:

## Corrected URLs
Was | Now
---- | ------
http://example.com/ | https://example.com/

**Comment by dkhamsing** [comment]
Good ideas, thanks for the feedback

**Comment by dkhamsing** [comment]
New pull title https://github.com/igorbarinov/awesome-data-engineering/pull/26

**Comment by dkhamsing** [comment]
@rshipp https://github.com/dkhamsing/frankenstein/commit/238c472a8f52bbc1eeca80b869f19fbb46af79a2

**Comment by rshipp** [comment]
Nice, thanks!

**Comment by dkhamsing** [comment]
@rshipp see https://github.com/dkhamsing/travis-playground/pull/32 :smile:

**Comment by rshipp** [comment]
:D :+1:
